name: CI Workflow

on:
  push:
    branches:
      - extend-tests
  pull_request:

jobs:
  style_check:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find src/ tests/ -name "*.cpp" -o -name "*.hpp" | xargs clang-format --dry-run -Werror

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libboost-test-dev libeigen3-dev libyaml-cpp-dev

      - name: Configure CMake
        run: |
          mkdir -p build && cd build
          cmake ..

      - name: Build Project
        run: |
          cd build
          make

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libboost-test-dev libeigen3-dev libyaml-cpp-dev

      - name: Configure CMake
        run: |
          mkdir -p build && cd build
          cmake ..

      - name: Build Project
        run: |
          cd build
          make
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
        